# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

orbs:
  aws-ecr: ttrahan/aws-ecr@dev:alpha

workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build_and_push_image:
          requires: 
            - build
          context: ttrahan
          region: us-west-2
          build-command: make
          account-url: 304170260410.dkr.ecr.us-west-2.amazonaws.com 
          repo: ttrahan-test
          tag: orb.${CIRCLE_BUILD_NUM}


